<a href="https://colab.research.google.com/github/lapnguyen331/machine_leaning_lab/blob/main/ML_class_lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Task 1.Python Programming**

In [ ]:
# task 1.1
L=[]
nega =0
posi =0

n= int(input("Nhập số nguyên n"))
for i in  range (n):
 temp= int(input("Nhập số nguyên thứ " +str(i) +":" ))
 L.append(temp);
 if temp < 0: nega +=1
 else: posi +=1
print("danh sách: "+str(L))
print("max: "+ str(max(L)))
print("min: "+ str(min(L)))
print("sum: "+ str(sum(L)))
print("sort acen: " +str(sorted(L)))
print("sort de: " + str(sorted(L,reverse = True)))
print("negative: " + str(nega))
print("positive: " +str(posi))

Nhập số nguyên n5
Nhập số nguyên thứ 0:-9
Nhập số nguyên thứ 1:-8
Nhập số nguyên thứ 2:56
Nhập số nguyên thứ 3:55
Nhập số nguyên thứ 4:88
danh sách: [-9, -8, 56, 55, 88]
max: 88
min: -9
sum: 182
sort acen: [-9, -8, 55, 56, 88]
sort de: [88, 56, 55, -8, -9]
negative: 2
positive: 3


In [ ]:
# task 1.2

n = int(input("nhập số nguyên n :"))
def recursion(n):
  if n <=1 : return 1;
  x=1;
  for i in range (1,int(n) +1):
       x*= i;
  return x+ recursion(n-1);
print("kết quả :"+str(recursion(n)))

nhập số nguyên n :4
kết quả :33


In [ ]:
# task 1.3
import functools as ft

class Account():
  def __init__(self ,name,email,country,friends,posts):
      self._name = name
      self._email =email
      self._country = country
      self._friends = friends
      self._posts = posts
  def getMaxLikePost(self):
    postval = self._posts[0]
    for post in self._posts:
      if post > postval : postval = post
    return postval


  def getMaxLikePostByFriend(self):
    maxpost = self.getMaxLikePost

    # for friend in self._friends:
    #   for post in friend._posts:
    #     if(post.__likes == maxpost.__likes):
    #       res= friend
    # return res

    return ft.reduce(lambda acc, curr: curr if (acc == None or acc.getMaxLikePost() < curr.getMaxLikePost()) else acc, self._friends, None)

  @property #viết lại hàm str
  def email(self):
    return self._email

  def moreThan(self):
    return len(self._posts) >= 10

  def isCountry(self,country):
    return str(self._country) == country

  def __str__(self):
    nl = '\n '
    return f'''
    [Tài khoản]
      Tên: {self._name}, email: {self._email}, country: {self._country}
      Danh sách bạn bè:
      [{', '.join(map(lambda friend: friend._email, self._friends))}]
      Danh sách bài viết:
      [{nl.join(map(lambda post: str(post), self._posts))}]'''

class AccountManager():
  def __init__(self, accounts):
    self.__accounts = accounts
  def groupAccountsByPostLike(self):
    return {
        True: list(filter(lambda x: x.moreThan, self.__accounts)),
        False: list(filter(lambda x: not x.moreThan, self.__accounts))
            }
  def filterAccounts(self, country):
    return list(filter(lambda x: x.isCountry(country), self.__accounts))
class Post():
  def __init__(self, content, subject, likes):
    self.__content = content
    self.__subject = subject
    self.__likes = likes
  def __gt__(self, other):
    return self.__likes > other.__likes
  def __str__(self):
    return f'''Tên bài viết: {self.__subject}, Lượt like: {self.__likes}'''

#mở rộng'
class VerifiedAccount(Account):
  def __init__(self, name, email, country, friends, posts, fromDate):
    self.__fromDate = fromDate
    super().__init__(name, email, country, friends, posts)
def __str__(self):
  nl = '\n '
  return f'''
  [Tài khoản xác minh]
    Tên: {self._name}, email: {self._email}, country: {self._country}, ngày tham gia: {self.__fromDate}
    Danh sách bạn bè:
    [{', '.join(map(lambda friend: friend._email, self._friends))}]
    Danh sách bài viết:
    [{nl.join(map(lambda post: str(post), self._posts))}]'''

class NomalProduct(Account):
  def __init__(self,name, email, country, friends, posts ):
    super().__init(name, email, country, friends, posts)

#unit test
account1 = Account('Lapne1', 'lapne@gmail.com', 'TP.HCM', [],
[
Post('Bài viết #1', 'Nội dung #1', 20),
Post('Bài viết #2', 'Nội dung #2', 2),
Post('Bài viết #3', 'Nội dung #3', 10),
Post('Bài viết #4', 'Nội dung #4', 5),
Post('Bài viết #5', 'Nội dung #5', 60)
])
account2 = Account('Hùng', 'hhhh5@gmail.com', 'Hà Nội', [account1],
[
Post('Bài viết #6', 'Nội dung #6', 10),
Post('Bài viết #7', 'Nội dung #7', 55),
Post('Bài viết #8', 'Nội dung #8', 20),
Post('Bài viết #9', 'Nội dung #9', 1),
Post('Bài viết #10', 'Nội dung #10', 3)
])
account3 = Account('Nam', 'nnnn@gmail.com', 'TP.HCM', [account1, account2],
[
  Post('Bài viết #11', 'Nội dung #11', 5),
  Post('Bài viết #12', 'Nội dung #12', 160),
  Post('Bài viết #13', 'Nội dung #13', 70),
  Post('Bài viết #14', 'Nội dung #14', 5),
  Post('Bài viết #15', 'Nội dung #15', 160),
  Post('Bài viết #16', 'Nội dung #16', 12),
  Post('Bài viết #17', 'Nội dung #17', 7),
  Post('Bài viết #18', 'Nội dung #18', 73),
  Post('Bài viết #19', 'Nội dung #19', 22),
  Post('Bài viết #20', 'Nội dung #20', 245),
  Post('Bài viết #21', 'Nội dung #21', 111)
])
account4 = VerifiedAccount('Kiệt', 'kiet@gmail.com', 'Tây Ninh', [account1, account3], [], '05/23/2087')
# account5 = NomalProduct('nomalName','nomalName@gmail.com','nomalProvince',[],[],'6/7/2003')
print(account1)
print(account2)
print(account3)
print(account4)
# print(account5)
manager1 = AccountManager([account1, account2, account3])
arr1 = manager1.groupAccountsByPostLike()[True]
arr2 = manager1.groupAccountsByPostLike()[False]
arr3 = manager1.filterAccounts('TP.HCM')
print(f'max post:{account3.getMaxLikePost()}')
print(f'Tài khoản bạn bè có post nhiều like nhất của Namlà: {account3.getMaxLikePostByFriend().email}')
print(f'Danh sách các tài khoản có nhiều hơn 10 post là: [{", ".join(map(lambda acc: acc.email, arr1))}]')
print(f'Danh sách các tài khoản có ít hơn 10 post là: [{", ".join(map(lambda acc: acc.email, arr2))}]')
print(f'Tập các tài khoản ở TP.HCM là: [{", ".join(map(lambda acc: acc.email, arr3))}]')




    [Tài khoản]
      Tên: Lapne1, email: lapne@gmail.com, country: TP.HCM
      Danh sách bạn bè:
      []
      Danh sách bài viết:
      [Tên bài viết: Nội dung #1, Lượt like: 20
 Tên bài viết: Nội dung #2, Lượt like: 2
 Tên bài viết: Nội dung #3, Lượt like: 10
 Tên bài viết: Nội dung #4, Lượt like: 5
 Tên bài viết: Nội dung #5, Lượt like: 60]

    [Tài khoản]
      Tên: Hùng, email: hhhh5@gmail.com, country: Hà Nội
      Danh sách bạn bè:
      [lapne@gmail.com]
      Danh sách bài viết:
      [Tên bài viết: Nội dung #6, Lượt like: 10
 Tên bài viết: Nội dung #7, Lượt like: 55
 Tên bài viết: Nội dung #8, Lượt like: 20
 Tên bài viết: Nội dung #9, Lượt like: 1
 Tên bài viết: Nội dung #10, Lượt like: 3]

    [Tài khoản]
      Tên: Nam, email: nnnn@gmail.com, country: TP.HCM
      Danh sách bạn bè:
      [lapne@gmail.com, hhhh5@gmail.com]
      Danh sách bài viết:
      [Tên bài viết: Nội dung #11, Lượt like: 5
 Tên bài viết: Nội dung #12, Lượt like: 160
 Tên bài viết: Nội dung #13, Lư

**Task 2.NumPy API**

In [ ]:
#task 2.1
import numpy as np
print(f'mảng từ 10 đến 25: {np.arange(10,26)}')
print(f'rever mảng: {np.arange(10,26)[::-1]}' )


mảng từ 10 đến 25: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]
rever mảng: [25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
#task 2.2
import numpy as np
input =[1,2,3,4]
print(f'Original array: {np.array(input)}')
print(f'Repeating 2 times: {np.array([input, input]).flatten()}')
print(f'Repeating 3 times: {np.array([input, input, input]).flatten()}')

Original array: [1 2 3 4]
Repeating 2 times: [1 2 3 4 1 2 3 4]
Repeating 3 times: [1 2 3 4 1 2 3 4 1 2 3 4]


In [ ]:
#task 2.3
input = [
[ 0.42, 0.48, 0.32],
[ 0.74, 0.58, 0.38],
[ 0.51 ,0.34, 0.15 ]
  ]
  #2d -> 1d
array = np.array(input)
print(f'Original array:\n {array}')
array[array >= 0.5] = 0.5
print(f'replaced array:{array}')

Original array:
 [[0.42 0.48 0.32]
 [0.74 0.58 0.38]
 [0.51 0.34 0.15]]
replaced array:[[0.42 0.48 0.32]
 [0.5  0.5  0.38]
 [0.5  0.34 0.15]]
